### PR TITLE
Add get quote from person

### LINKED ISSUE #13: Implement endpoint to get a Quote from a Person

### PR DESCRIPTION
**Pull request by bellkelly**
# Overview

Implement the endpoint to get a quote from a user.

To fetch a quote from a user: `GET people/<slack_user_id>/quotes/<id>`

The body contains the `id` of the quote, the `content` of the quote, the `person_id` which is the `slack_user_id` of the person that said the quote, and the `created` timestamp of the quote.

# Notes

- The new black + flake8 pipeline stuff was complaining a bunch and forced me to make a bunch of unrelated updates.
- I refactored some of the API tests to separate person and quote tests.

# References

references #13

### CODE REVIEW

**Comment by revangel** [comment]
# DevQA (+1)
- [x] Can get existing Quote from existing Person with correct body
- [x] Non-existing Quotes are handled appropriately

**Comment by revangel** [comment]
# Code (+1)

Some notes while reviewing
- I wonder if we should have a "contentId" for Quotes since it felt somewhat unintuitive to try something like `<api>/person/<person_id>/quotes/1` and then find out that their Quote with id==1 doesn't exist since their first quote is Quote with id==5.
  - Then again, if we have a "contentId", it doesn't solve the fact that you can't sequentially navigate through a Person's quotes without knowing what they are
  - So maybe it's ok



- Reviewing this PR reminded me of a feature which I filled out in https://github.com/revangel/nostalgiabot2/issues/64

**Comment by bellkelly** [comment]
>     * I wonder if we should have a "contentId" for Quotes since it felt somewhat unintuitive to try something like `<api>/person/<person_id>/quotes/1` and then find out that their Quote with id==1 doesn't exist since their first quote is Quote with id==5.

Honestly, as I was writing this, I was wondering if it was even worthwhile. I doubt we even use this endpoint. Another thought I had as I read your idea for a contentId, is that we could also have an ordinal (either real or perceived). We could increment an ordinal in the db for each new quote by a person and look up based on that. Or just order by `created` and index into the results. Maybe we see if this endpoint is even useful first. If it's useful, but could benefit from a different identifier to get the quote, we can update it. 

I agree, that a search filter will be way more useful, as you said. Also, we might want an end point for getting a random quote from a person. I can't remember if we have a ticket for that, but I could add one if we don't.

**Comment by revangel** [comment]
> > ```
> > * I wonder if we should have a "contentId" for Quotes since it felt somewhat unintuitive to try something like `<api>/person/<person_id>/quotes/1` and then find out that their Quote with id==1 doesn't exist since their first quote is Quote with id==5.
> > ```
> 
> Honestly, as I was writing this, I was wondering if it was even worthwhile. I doubt we even use this endpoint. Another thought I had as I read your idea for a contentId, is that we could also have an ordinal (either real or perceived). We could increment an ordinal in the db for each new quote by a person and look up based on that. Or just order by `created` and index into the results. Maybe we see if this endpoint is even useful first. If it's useful, but could benefit from a different identifier to get the quote, we can update it.
> 
> I agree, that a search filter will be way more useful, as you said. Also, we might want an end point for getting a random quote from a person. I can't remember if we have a ticket for that, but I could add one if we don't.

Yeah exactly - I didn't really want to say I wonder if this endpoint is useful since you just finished some work on it haha!

I like the idea of a perceived ordinal on `created`. I don't think it really make sense to have an actual ordinal field though since how does one order quotes in general?

Otherwise, I don't really think there's much benefit to having a "contentId" for quotes.

I think Remember (#17) and Quote (#19) are the feature tickets for getting a random quote from a person. At that level, it could probably be the service that just randomizes something. I don't even know if it'll go through this endpoint.

**Comment by bellkelly** [comment]
> Yeah exactly - I didn't really want to say I wonder if this endpoint is useful since you just finished some work on it haha!
> 
> I like the idea of a perceived ordinal on `created`. I don't think it really make sense to have an actual ordinal field though since how does one order quotes in general?
> 
> Otherwise, I don't really think there's much benefit to having a "contentId" for quotes.
> 
> I think Remember (#17) and Quote (#19) are the feature tickets for getting a random quote from a person. At that level, it could probably be the service that just randomizes something. I don't even know if it'll go through this endpoint.

Ok, I'll merge this for now. And if it turns out it's not useful, we can remove it easily. And if it needs to be tweaked later to be useful, that shouldn't be hard either :)

**Pull request merged**
